default: &default
  adapter: mysql2
  encoding: utf8
  pool: 5
  username: root
  password: remeta

development:
  <<: *default
  database: student_job_development

test:
  <<: *default
  database: student_job_test

production:
  <<: *default
  database: student_job_production
